---
##########################
# docker

docker_user: "{{ operator_user }}"

##########################
# operator

operator_user: dragon

# yamllint disable rule:line-length
operator_public_key: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQC2wE2xiuO+i3qmDvu8kCCKX7U7H1diOICbWmR2UrKIxqWgcfWMQsT3WclotJKuVJuKIWyFD6ZNwwLuvC3RxVSqhCiWjqxg3jzJBj7/C1O3IYyLGTUl/x7Cky530lf/aj4wrwt3Ketk/4QNwgget2nCvOy0S2NDCJ3rL6oIUjdJekvRrFf9IbWeX8fqYYCoh1cYJWto1XYPnhMDAB/lqtjN1ssurLSKoJg/bUT7q/KkIvvA/BOR2NMqS0aGx+bKhdkeB22V/t75Ct8ymoCYk9+MTC9i/QX20Fi7835/W7Gl18J8NiO9ebaWyYbsxZ5klWXQa5EiLLBDZ82OR88G+0FjXp1Z3VG6FcpdYpW7sxrT21HEvWOnQACZCdlzwyBJ31id/LjDRhJU6BmZm0Sa9EOJNL8XVOUUzuoa0XL1mIVTsmLpUwqLSfw6Ditb+q4afFi0iYMe3JKOt+JmftvBgeQCjNUsCzk+Ny2j6dZKv2aeF5LOQZGRM3HzG39Gkir3q1zdWmCl4lc3QQBfr5ZcdAp+wQMFSgJAudKffO9kdDVNoyjgih7rD3E+JjJdhY9//WQEEBm2vfEqm7qqEQUAELd0JBCivJmOhUVH0rGbTrnkTBtLR4Au40W5aYaNQJ7+U3hTRrvpycSC1pUU3Wq3OXJd2FRDgKQJljQcpBw4V9j8GQ==
# yamllint enable rule:line-length

operator_authorized_keys:
  - "{{ operator_public_key }}"

##########################
# resolvconf

resolvconf_nameserver:
  - 8.8.8.8
  - 9.9.9.9
resolvconf_search: int1.landscape.sovereignit.de

##########################
# hosts

hosts_type: template
hosts_additional_entries:
  api-int.int1.landscape.sovereignit.de: 192.168.32.9
  api.int1.landscape.sovereignit.de: 192.168.96.9

##########################
# chrony

chrony_servers:
  - ptbtime1.ptb.de
  - ptbtime2.ptb.de
  - ptbtime3.ptb.de
chrony_allowed_subnets:
  - 127.0.0.1/32

##########################
# ceph

ceph_cluster_fsid: 44bc2d19-fd83-4b92-a6c4-eed358e35672
