
motd_content: |
  .
   ____   ____ ____    _                    _
  / ___| / ___/ ___|  | |    __ _ _ __   __| |___  ___ __ _ _ __   ___
  \___ \| |   \___ \  | |   / _` | '_ \ / _` / __|/ __/ _` | '_ \ / _ \
   ___) | |___ ___) | | |__| (_| | | | | (_| \__ \ (_| (_| | |_) |  __/
  |____/ \____|____/  |_____\__,_|_| |_|\__,_|___/\___\__,_| .__/ \___|
                                                           |_|
